# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc406962f47cf151b4ae1922c39cf371c18d6dce3f4dd8addf3d4d1fab9b24c938eae6db4e8350b03b25e177e7d2ad2b83c140016da26492400234d83d1f664

test:
  secret_key_base: 5cf9d435063e276a17509f9b0ebfe78dcf00a61c1fe20b11626dc9878390dd52830b65787f26f3fe57e897f8895f3b2df10fe6d6d898333a8c7c068466f3d6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
